name: $(date:yyyyMMdd)$(rev:.r)

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  dotNetCoreVersion: 2.2.401
  cakeVersion: 0.34.1

trigger:
- master
- develop
- bugfix/*
- feature/*

pr:
- master
- develop

jobs:
- template: template/build.yml # Run Windows build and tests.
  parameters:
    name: Windows
    vmImage: windows-2019
    dotNetCoreVersion: $(dotNetCoreVersion)
    cakeVersion: $(cakeVersion)
    testFilter: FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Windows

- template: template/build.yml # Run Linux build and tests.
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    dotNetCoreVersion: $(dotNetCoreVersion)
    cakeVersion: $(cakeVersion)
    testFilter: FullyQualifiedName~DotNet.Testcontainers

- job: Publish # Publish static code analysis and a new version of .NET Testcontainers.
  displayName: Publish new version
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))

  dependsOn:
  - Windows
  - Linux

  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK $(dotNetCoreVersion)
    inputs:
      version: $(dotNetCoreVersion)

  - powershell: ./build.sh --target=Sonar
    displayName: Sonar
    env:
      SONARQUBE_URL: $(sonarcloud.url)
      SONARQUBE_KEY: $(sonarcloud.key)
      SONARQUBE_TOKEN: $(sonarcloud.token)
      SONARQUBE_ORGANIZATION: $(sonarcloud.organization)

  - powershell: ./build.sh --target=Publish
    displayName: Publish
    env:
      NUGET_SOURCE: $(feed.source)
      NUGET_APIKEY: $(feed.apikey)
