name: $(date:yyyyMMdd)$(rev:.r)

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  MSBUILDDISABLENODEREUSE: true # https://github.com/dotnet/sdk/issues/9452
  DECODE_PERCENTS: true # https://github.com/microsoft/azure-pipelines-agent/pull/3152
  TZ: CET # https://stackoverflow.com/q/53510011
  dotNetCoreVersion: 5.0.201
  cakeVersion: 1.0.0

trigger:
  - master
  - develop
  - bugfix/*
  - feature/*

pr:
  - master
  - develop

jobs:
  # Run Windows build and tests.
  - template: .azuredevops/build.yml
    parameters:
      name: BuildAndTestsOnWindows
      displayName: Windows
      vmImage: windows-2019
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Containers.Windows

  # Run Unix build and tests.
  - template: .azuredevops/build.yml
    parameters:
      name: BuildAndTestsOnUnix
      displayName: Unix
      vmImage: ubuntu-18.04
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers

  # Run static code analysis and publish artifact.
  - template: .azuredevops/publish.yml
    parameters:
      name: Release
      displayName: Release
      vmImage: ubuntu-18.04
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
