site_name: Testcontainers for .NET
site_url: https://dotnet.testcontainers.org
repo_name: testcontainers-dotnet
repo_url: https://github.com/testcontainers/testcontainers-dotnet
edit_uri: edit/develop/docs/
theme:
  name: material
  custom_dir: docs/theme
  palette:
    scheme: testcontainers
  font:
    text: Roboto
    code: Roboto Mono
  favicon: favicon.ico
  logo: logo.svg
extra_css:
  - css/extra.css
  - css/tc-header.css
plugins:
  - markdownextradata
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - index.md
  - cicd/index.md
  - custom_configuration/index.md
  - api/create_docker_image.md
  - api/create_docker_container.md
  - api/create_docker_network.md
  - api/low_level_api_access.md
  - api/resource_reaper.md
  - api/resource_reuse.md
  - api/wait_strategies.md
  - api/connection_string_provider.md
  - api/best_practices.md
  - dind/index.md
  - full_framework/index.md
  - test_frameworks/xunit_net.md
  - Examples:
    - examples/aspnet.md
  - Modules:
    - modules/index.md
    - modules/activemq.md # Apache
    - modules/cassandra.md # Apache
    - modules/pulsar.md # Apache
    - modules/eventhubs.md # Azure
    - modules/servicebus.md # Azure
    - modules/clickhouse.md
    - modules/db2.md
    - modules/elasticsearch.md
    - modules/grafana.md
    - modules/mongodb.md
    - modules/mssql.md
    - modules/neo4j.md
    - modules/opensearch.md
    - modules/playwright.md
    - modules/postgres.md
    - modules/qdrant.md
    - modules/questdb.md
    - modules/rabbitmq.md
    - modules/toxiproxy.md
  - contributing.md
  - contributing_docs.md